version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: ./development.dockerfile
    depends_on:
      db:
        condition: service_started
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    restart: always
    environment:
      PORT: :5000
      DB_URL: postgres://postgres:pewpew@db:5432/eltech-bloggers

  db:
    image: postgres:16.2
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pewpew
      POSTGRES_DB: eltech-bloggers
      restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
