services:
  api:
    build:
      context: ./
      dockerfile: ./dockerfile
    depends_on:
      db:
        # condition: service_healthy
        condition: service_started
    ports:
      - 5000:5000
    # volumes:
    #   - ./:/server
    restart: always
    environment:
      PORT: :5000
      DB_URL: postgres://postgres:pewpew@db:5432/eltech-bloggers

  db:
    image: postgres:16.2
    container_name: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pewpew
      POSTGRES_DB: eltech-bloggers
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 5432

  migrator:
    build:
      context: .
      dockerfile: ./Dockerfile.migration
    depends_on:
    db:
      condition: service_started
    environment:
      TERN_CONFIG: ./tern.conf
      TERN_MIGRATIONS: ./migrations/
      POSTGRES_PASSWORD: pewpew
      POSTGRES_DB: eltech-bloggers
      POSTGRES_HOST: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
